/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class FeedbackForm extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackForm
     */
    public FeedbackForm() {
        initComponents();
        setSize(400,445);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Give Your Feedback Here");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Feedback Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 200, 60);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 100, 40);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Feedback:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 110, 40);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rating:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 90, 40);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 65)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LabMa!l.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 10, 290, 80);

        t1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(170, 150, 200, 40);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("2");
        r2.setOpaque(false);
        getContentPane().add(r2);
        r2.setBounds(150, 210, 50, 33);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("3");
        r3.setOpaque(false);
        getContentPane().add(r3);
        r3.setBounds(200, 210, 50, 33);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("4");
        r4.setOpaque(false);
        getContentPane().add(r4);
        r4.setBounds(250, 210, 50, 33);

        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("5");
        r5.setOpaque(false);
        getContentPane().add(r5);
        r5.setBounds(300, 210, 50, 33);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("1");
        r1.setOpaque(false);
        getContentPane().add(r1);
        r1.setBounds(100, 210, 50, 33);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 270, 280, 86);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 370, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wp-6.1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String f_name=t1.getText().trim();
        int rating=0;
        String feedback=ta1.getText().trim();
        if(r1.isSelected())
            rating=1;
        if(r2.isSelected())
            rating=2;
        if(r3.isSelected())
            rating=3;
        if(r4.isSelected())
            rating=4;
        if(r5.isSelected())
            rating=5;
        if(rating==0)
            JOptionPane.showMessageDialog(this,"Kindly select a rating for our application.");
       if((rating!=0)||(f_name.equals(""))||(feedback.equals(""))){
           try{
               Class.forName("java.sql.DriverManager");
               Connection conn= DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail","root","psbb");
               String q ="insert into feedback values('"+f_name+"',"+rating+",'"+feedback+"')"; 
                Statement stmt= conn.createStatement();
                stmt.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"Thank you for your valuable feedback.");
                close();
           }
           catch(Exception e){
                               JOptionPane.showMessageDialog(this,"An unexpected error has occured."
                        + "\nWe shall rectify the problem soon."
                        + "\nSorry for the inconvenience.");
                this.setVisible(false);
       }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        IntroFrame i=new IntroFrame();
        i.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
