
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kkn-elective
 */
public class MsgScr extends javax.swing.JFrame {

    /**
     * Creates new form MsgScr
     */
    public MsgScr() {
        initComponents();
        setSize(400,330);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        ta1.setText("");
        int mail_rec=MailScreen.recno;
            try{
                Class.forName("java.sql.DriverManager");
                conn= DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail","root","psbb");
                String q="Select message,sender from "+Login.uid+" where s_no="+mail_rec;
                stmt=conn.createStatement();
                rs=stmt.executeQuery(q);
               while(rs.next()){
                                      String msg=rs.getString("message");
                                      String sndr=rs.getString("sender");
                                      ta1.append(msg);
                                      if(MailScreen.flag==false)
                                      l1.setText(sndr+" has sent you the following:");
                                      else if(MailScreen.flag==true)
                                          l1.setText("You have sent the following:");
}
}
catch(Exception e){
   JOptionPane.showMessageDialog(this,"An unexpected error has occured."
                        + "\nWe shall rectify the problem soon."
                        + "\nSorry for the inconvenience.");
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        l1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Message");
        getContentPane().setLayout(null);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        ta1.setRows(5);
        ta1.setText("\n");
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 83, 370, 200);

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(51, 255, 204));
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(l1);
        l1.setBounds(10, 10, 370, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msgscr-1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    Connection conn;
    ResultSet rs;
    Statement stmt;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgScr().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    public static javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
