import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kkn-elective
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setSize(600,730);
        setResizable(false);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        question = new javax.swing.JComboBox();
        p2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registration");
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("Copperplate Gothic Light", 3, 36)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messageicon2_1.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 256, 206);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LabMa!l.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 230, 290, 80);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Enter a username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 340, 290, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Enter a password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 390, 290, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Type a suitable answer:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 550, 290, 30);

        t1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(330, 340, 260, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Choose a security question:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 500, 290, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Confirm the password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 440, 290, 30);

        answer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        getContentPane().add(answer);
        answer.setBounds(330, 550, 260, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addacc.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 610, 100, 100);

        p1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        getContentPane().add(p1);
        p1.setBounds(330, 390, 260, 40);

        question.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        question.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is the name of your pet?", "What is the maiden name of your mother?", "Which is your favorite TV sitcom?", "Who is your best friend?", "What is your favorite food?", "Where did you attend middle school?", "Who is your favorite athlete?", "What is the name of your hometown?", "Where did your father study?", " " }));
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });
        getContentPane().add(question);
        question.setBounds(330, 500, 260, 40);

        p2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        getContentPane().add(p2);
        p2.setBounds(330, 440, 260, 40);

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regwp.png"))); // NOI18N
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // To create a new account:
        String ques=(String)question.getSelectedItem();
        String ans=answer.getText().trim();
        String uname=t1.getText().trim();
        String pass= new String(p1.getPassword());
        String passcheck= new String(p2.getPassword());
        int l1=uname.length();
        int l2=pass.length();
        int l3=passcheck.length();
        int l4=ans.length();
        int k=0;
        if(uname.contains(" ")){
        JOptionPane.showMessageDialog(this,"Spaces aren't allowed in username.");
        t1.setText("");
        }
        else{
         if(l1==0||l2==0||l3==0||l4==0)
            JOptionPane.showMessageDialog(this,"Do not leave any field empty.");
        if(l1<6||l2<6||l3<6)
            JOptionPane.showMessageDialog(this,"Enter a username and password with more than 6 characters\nand less than 35 characters");

       
         if((l1<=35)&&(l1>=6)&&(l2<=35)&&(l2>=6)&&(l3<=35)&&(l3>=6)){
             if(l4<=50){
         if(pass.equals(passcheck))
            
        {       
            try{
                Class.forName("java.sql.DriverManager");
                Connection conn= DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail","root","psbb");
                String q2 = "select count(*) from login where username="+"'"+uname+"'";
                Statement stmt2= conn.createStatement();
                ResultSet count=stmt2.executeQuery(q2);
                while(count.next()){
                     k=count.getInt("count(*)");
                }         
                if(k>0){
                    JOptionPane.showMessageDialog(this,"Username already exists, choose another name.");
                }
                else if(k==0){
                    try{
                Class.forName("java.sql.DriverManager");
                Connection conn1= DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail","root","psbb");
                String q= "insert into login values('"+uname+"','"+pass+"','"+ques+"','"+ans+"')";
                String q1="create table "+uname+"(S_No int(5) primary key,R_Date varchar(19), Sender varchar(35), Message varchar(65000))";
                Statement stmt1=conn1.createStatement();
                Statement stmt= conn1.createStatement();
                stmt.executeUpdate(q);
                stmt1.execute(q1);
                Class.forName("java.sql.DriverManager");
                Connection conn2= DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail_sent","root","psbb");
                String p="create table "+uname+"(S_No int(5) primary key, Receiver varchar(35), S_Date varchar(19), Message varchar(65000))";
                Statement stmte=conn2.createStatement();
                stmte.execute(p);
                JOptionPane.showMessageDialog(this,"Registration successful!");
                 IntroFrame i=new IntroFrame();
                 i.setVisible(true);
                 close();
                     }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(this,ex.getMessage());
            }
            }
            }
            catch(Exception ex){
               JOptionPane.showMessageDialog(this,"Error1");
                close();
             }
        }
          else
            JOptionPane.showMessageDialog(this,"Passwords do not match.");
             }
             else
                 JOptionPane.showMessageDialog(this,"Enter an answer less than 50 characters");
        }
        else
             JOptionPane.showMessageDialog(this,"Do not exceed 35 characters");
       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // to go back to IntroScreen:
        IntroFrame i=new IntroFrame();
        i.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_t1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JComboBox question;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
