
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.*;
import java.util.Date;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kkn-elective
 */
public class WriteScreen extends javax.swing.JFrame {

    /**
     * Creates new form WriteScreen
     */
    public WriteScreen() {
        initComponents();
        setSize(409,445);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        send = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Write Your Message");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Message Editor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 271, 36);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(280, 330, 80, 80);

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rocketsendsmall.png"))); // NOI18N
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        getContentPane().add(send);
        send.setBounds(50, 330, 80, 80);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 60, 30);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        ta1.setLineWrap(true);
        ta1.setRows(5);
        ta1.setTabSize(6);
        ta1.setToolTipText("Write Your Message Here");
        ta1.setWrapStyleWord(true);
        ta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        ta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ta1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 360, 190);

        t1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(70, 60, 240, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wp-1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 410, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        // to send the message:
        String uname=t1.getText().trim();
        String msg=ta1.getText().trim();
        int msgc=0,userc=0,sboxc=0;
        int l1=uname.length();
        int l2=msg.length();
        DateFormat df = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date d=new Date();
        String sdate=(df.format(d));
        if(l1!=0&&l2!=0){
        try{
            Class.forName("java.sql.DriverManager");
            Connection c=DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail","root","psbb");
            Connection c1=DriverManager.getConnection("jdbc:mysql://192.168.10.184/labmail_sent","root","psbb");
            String q2 = "select count(*) from "+uname;
            String q3="select count(*) from login where username='"+uname+"'";
            String p2="select count(*) from "+Login.uid;
            Statement stmt2= c.createStatement();
            Statement stmt3=c.createStatement();
            Statement stmt4=c1.createStatement();
            Statement stmt5=c1.createStatement();
            ResultSet count=stmt2.executeQuery(q2);
            ResultSet ucount=stmt3.executeQuery(q3);
            ResultSet scount=stmt4.executeQuery(p2);
            while(ucount.next()){
                userc=ucount.getInt("count(*)");
            }
            while(count.next()){
                msgc=count.getInt("count(*)");
                }
            while(scount.next()){
                sboxc=scount.getInt("count(*)");
            }
            if(userc==0)
                JOptionPane.showMessageDialog(this,"The specified user does not exist.");
            else if(msg.equals(""))
                    JOptionPane.showMessageDialog(this,"Enter a message to send");
            else{
                    uname=t1.getText();
                    msgc++;
                    sboxc++;
                    Statement stmt=c.createStatement();       
                    String q="insert into "+uname+" values("+msgc+",'"+sdate+"','"+Login.uid+"','"+msg+"')";
                    stmt.executeUpdate(q);
                    String p="insert into "+Login.uid+" values("+sboxc+",'"+uname+"','"+sdate+"','"+msg+"')";
                    stmt5.executeUpdate(p);
                    JOptionPane.showMessageDialog(this,"Message sent successfully!");
                    this.setVisible(false);
                    
                }            
        }  
        catch(Exception e){
                            JOptionPane.showMessageDialog(this,"An unexpected error has occured."
                        + "\nWe shall rectify the problem soon."
                        + "\nSorry for the inconvenience.");
                close();
            
        }
        }
        else if(l1==0)
            JOptionPane.showMessageDialog(this,"Enter a username");
        else if(l2==0)
            JOptionPane.showMessageDialog(this,"Type a message");
        
    }//GEN-LAST:event_sendMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // to clear the message:
        ta1.setText("");
    }//GEN-LAST:event_deleteMouseClicked

    private void ta1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ta1KeyPressed
        // to display the number of characters:
        String temp=ta1.getText();
       int templ=temp.length();
       ta1.setToolTipText("You have "+(65000-templ)+" characters left.");
       if(templ==65000){
           JOptionPane.showMessageDialog(this,"You've reached the maximum limit of characters.");
           ta1.setEditable(false);
       }
           
       
    }//GEN-LAST:event_ta1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static int k=0;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WriteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WriteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WriteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WriteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WriteScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel send;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
